### ISSUE TITLE
[Backend] Set DB Table Entities related to Games

### ISSUE THREAD

**Issue by refigo** [webPongServ/pongserv#25]
### TODO
- [x] TB_GM01L  게임내역
- [x] TB_GM01D  게임상세
- [x] TB_GM02S  유저별게임통계
- [x] TB_GM03D 게임옵션상세
- [x] TB_GM04L 레더대기내역
