### ISSUE TITLE
[Backend] 모든 Entity에 @PrimaryGeneratedColumn 추가하기

### ISSUE THREAD

**Issue by refigo** [webPongServ/pongserv#51]
### TODO

- [x] Entities in Users
- [x] Entities in Chats
- [x] Entities in Games
- [x] Common Entity
