### ISSUE TITLE
[Backend] Implementation Chatrooms User Listing API

### ISSUE THREAD

**Issue by refigo** [webPongServ/pongserv#61]
### TODO
- [x] GET /chats/users
- [x] PUT /chats/kick
- [x] POST /chats/ban
- [x] POST /chats/mute
- [x] POST /chats/empowerment
- [x] POST /chats/game-request
